### ISSUE TITLE
Trying out LPV ... getting nothing!

### ISSUE THREAD

**Issue by rquadling** [raphaelstolt/lean-package-validator#16]
### Expected behavior
Something added to my .gitattributes file regarding ignoring of exports.

### Actual behavior
Nothing changed.

### Steps to reproduce actual behavior
Installed LPV globally.
Changed directory to my rquadling/lalit repo.
Ran `lpv validate . --enforce-strict-order --overwrite`.

I get the output of ...
```
✔ 2016-10-05 09:49:00 richardquadling@Richards-MacBook-Pro:~/dev/php/lalit $  [master|✔]$ lpv validate . --enforce-strict-order -o

The present .gitattributes file is considered invalid.

Overwrote it with the shown content:
# Auto detect text files and perform LF normalization
*     text=auto

# Force text mode
*.php text diff=php
*.xml text

/tests/bugs/*.php diff=php eol=lf
```

But the output is the original file.

I'm expecting the various MarkDown files, the tests, etc. to be added.

**Comment by rquadling** [comment]
Oh! This is how I get started on a package. I find a bug and then try and fix it. End up becoming a contributor and eventually collaborator. Hope this one isn't too hard to fix.

**Comment by raphaelstolt** [comment]
Already wip on my end.

**Comment by raphaelstolt** [comment]
Closed with 5dd5ce94ad40863b4ee108bf3f4b2db933b082f9.

**Comment by raphaelstolt** [comment]
Thanks for the error report. :open_hands:

**Comment by rquadling** [comment]
Looks good! Already using it on several of my packages and seeing the result.
