### ISSUE TITLE
Add link to the lean-package-validator GitHub repo

### ISSUE THREAD

**Issue by raphaelstolt** [raphaelstolt/lean-package-validator#25]
In created or modified `.gitattributes` files a link to the lean-package-validator GitHub repo is added to increase the project's visibility.

**Comment by lalitvj** [comment]
Hello raphaelstolt,

Can you help me what I need to do on this issue? Not able to get it.

**Comment by raphaelstolt** [comment]
Hi @lalitvj,

this issue is all about adding a header comment to the `.gitattributes` file when creating or modifying them.

When creating a `.gitattributes` file, via `lean-package-validator validate [<directory>] --create|--overwrite`, the following header should be added as a comment at the top of the file: `This file was generated by the lean package validator (http://git.io/lean-package-validator).`. 

When modifing an existing `.gitattributes` file, via `lean-package-validator validate [<directory>] --overwrite`, the following header should be added as a comment at the top of the file: `This file was partially modified by the lean package validator (http://git.io/lean-package-validator).`

It would also be nice to have an option e.g. `--without-headers` which disables the header generation if desired. 

For creating and getting pull request accepted have a look at the [CONTRIBUTING.md](https://github.com/raphaelstolt/lean-package-validator/blob/master/.github/CONTRIBUTING.md) file.

**Comment by raphaelstolt** [comment]
Done with 80e8d7fabc855f0aa4477e01c6d0e3a40f1222d5.
