### ISSUE TITLE
Create distributable PHAR

### ISSUE THREAD

**Issue by raphaelstolt** [raphaelstolt/lean-package-validator#27]
It would be nice to distribute the lean package validator via a PHAR file.

**Comment by theofidry** [comment]
Unless you have anything special, https://github.com/humbug/box should work well and then you can configure a Travis deployment on releases, see https://medium.com/@tfidry/create-and-deploy-secure-phars-c5572f10b4dd (you can skip the signing part of the PHAR - I should deprecate it from the article

**Comment by raphaelstolt** [comment]
Closed with c76b8385223a940b5d19a8d1ff47fe0caba7a8b1.
